"""The schema, with the corrections the old one needed.

Ported from ``drizzle/schema.ts``, which was the only valid description of the database —
the six checked-in migrations were MySQL and one table had never been migrated at all.
Since the baseline is being written from scratch, the defects went with it:

* **two enums were both named ``status``** (``drizzle/schema.ts:38`` and ``:93``), which
  PostgreSQL cannot create twice. Every enum now has a distinct, table-scoped name.
* **no index on the columns every query filters by** — ``policies.user_id``,
  ``check_history(user_id, created_at)``, ``developer_api_keys.user_id``,
  ``image_uploads.api_key_id``. Each was the sole predicate of its only query.
* **``updated_at`` never changed**, yet the policy list ordered by it — so the list was
  really ordered by creation time. A trigger now maintains it.
* **naive timestamps**, which depend on the server's TimeZone. All are ``timestamptz``.
* **no CHECK constraints at all**, so a confidence of 4000 or a malformed digest could be
  stored. The ones that encode a real invariant are now enforced by the database.

snake_case throughout. The wire format stays camelCase, so no client field name changes.
"""

from __future__ import annotations

from datetime import datetime
from typing import Any

from sqlalchemy import (
    ARRAY,
    BigInteger,
    Boolean,
    CheckConstraint,
    DateTime,
    Enum,
    ForeignKey,
    Index,
    Integer,
    String,
    Text,
    text,
)
from sqlalchemy.dialects.postgresql import INET, JSONB
from sqlalchemy.orm import Mapped, mapped_column

from contentfirewall.db.base import Base, utc_now_column

# Every enum is named for the column it serves. The old schema reused "status" for two
# different value sets, which is a hard conflict in PostgreSQL.
USER_ROLE = Enum("user", "admin", name="user_role")
SUBSCRIPTION_STATUS = Enum("trial", "active", "expired", "cancelled", name="subscription_status")
API_KEY_STATUS = Enum("active", "revoked", name="api_key_status")
POLICY_ACTION = Enum("blur", "block", "warn", name="policy_action")
CHECK_INPUT_TYPE = Enum("text", "image", name="check_input_type")
CHECK_DECISION = Enum("allow", "blur", "block", "warn", "uncertain", name="check_decision")
CACHE_STATUS = Enum("fresh", "cached", name="cache_status")
AUDIT_ACTOR_TYPE = Enum(
    "session_user", "api_key", "extension_token", "system", name="audit_actor_type"
)


def _pk() -> Mapped[int]:
    """``bigint generated by default as identity`` — not ``serial``.

    ``serial`` is legacy: its sequence ownership is implicit, which makes it awkward to
    grant, rename or detach. Identity columns are the standard replacement, and ``bigint``
    costs nothing now against a migration nobody wants later.
    """
    return mapped_column(BigInteger, primary_key=True, autoincrement=True)


class User(Base):
    __tablename__ = "users"

    id: Mapped[int] = _pk()
    open_id: Mapped[str] = mapped_column(String(64), nullable=False, unique=True)
    name: Mapped[str | None] = mapped_column(Text)
    email: Mapped[str | None] = mapped_column(String(320))
    login_method: Mapped[str | None] = mapped_column(String(64))
    role: Mapped[str] = mapped_column(USER_ROLE, nullable=False, server_default="user")
    last_signed_in: Mapped[datetime] = utc_now_column()
    created_at: Mapped[datetime] = utc_now_column()
    updated_at: Mapped[datetime] = utc_now_column()

    __table_args__ = (
        CheckConstraint("char_length(open_id) between 1 and 64", name="open_id_length"),
    )


class Subscription(Base):
    __tablename__ = "subscriptions"

    id: Mapped[int] = _pk()
    # Unique, and load-bearing: the trial upsert relies on it to be safe under concurrent
    # first requests. Without it two requests can each grant a trial.
    user_id: Mapped[int] = mapped_column(
        BigInteger, ForeignKey("users.id", ondelete="CASCADE"), nullable=False, unique=True
    )
    plan_code: Mapped[str] = mapped_column(String(64), nullable=False, server_default="trial")
    status: Mapped[str] = mapped_column(SUBSCRIPTION_STATUS, nullable=False, server_default="trial")
    trial_started_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    trial_ends_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    current_period_start: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    current_period_end: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    cancel_at_period_end: Mapped[bool] = mapped_column(Boolean, nullable=False, server_default="false")
    cancelled_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    stripe_customer_id: Mapped[str | None] = mapped_column(String(255))
    stripe_subscription_id: Mapped[str | None] = mapped_column(String(255))
    created_at: Mapped[datetime] = utc_now_column()
    updated_at: Mapped[datetime] = utc_now_column()

    __table_args__ = (
        CheckConstraint("trial_ends_at > trial_started_at", name="trial_window"),
        # Both ends of a paid period exist, or neither does. A half-set period is how an
        # entitlement check silently reads as "no access".
        CheckConstraint(
            "(current_period_start IS NULL) = (current_period_end IS NULL)", name="period_pair"
        ),
        CheckConstraint(
            "current_period_end IS NULL OR current_period_end > current_period_start",
            name="period_order",
        ),
    )


class Policy(Base):
    __tablename__ = "policies"

    id: Mapped[int] = _pk()
    user_id: Mapped[int] = mapped_column(
        BigInteger, ForeignKey("users.id", ondelete="CASCADE"), nullable=False
    )
    name: Mapped[str] = mapped_column(String(120), nullable=False)
    source_preference: Mapped[str] = mapped_column(Text, nullable=False)
    language: Mapped[str] = mapped_column(String(8), nullable=False)
    action: Mapped[str] = mapped_column(POLICY_ACTION, nullable=False)
    scope_text: Mapped[bool] = mapped_column(Boolean, nullable=False, server_default="true")
    scope_images: Mapped[bool] = mapped_column(Boolean, nullable=False, server_default="true")
    rules: Mapped[list[dict[str, Any]]] = mapped_column(JSONB, nullable=False)
    version: Mapped[int] = mapped_column(Integer, nullable=False, server_default="1")
    created_at: Mapped[datetime] = utc_now_column()
    updated_at: Mapped[datetime] = utc_now_column()

    __table_args__ = (
        # The list is filtered by user_id and ordered by updated_at DESC, and had no index
        # at all. Declared DESC so the ordering is served by the index rather than a sort.
        Index("ix_policies_user_updated", "user_id", text("updated_at DESC")),
        CheckConstraint("jsonb_typeof(rules) = 'array'", name="rules_is_array"),
        CheckConstraint("jsonb_array_length(rules) between 1 and 12", name="rules_count"),
        CheckConstraint("char_length(name) between 2 and 120", name="name_length"),
        CheckConstraint("version >= 1", name="version_positive"),
    )


class CheckHistory(Base):
    __tablename__ = "check_history"

    id: Mapped[int] = _pk()
    user_id: Mapped[int] = mapped_column(
        BigInteger, ForeignKey("users.id", ondelete="CASCADE"), nullable=False
    )
    # SET NULL, not CASCADE: deleting a policy must not erase the record that a check
    # happened. The history is the user's, not the policy's.
    policy_id: Mapped[int | None] = mapped_column(
        BigInteger, ForeignKey("policies.id", ondelete="SET NULL")
    )
    input_type: Mapped[str] = mapped_column(CHECK_INPUT_TYPE, nullable=False)
    input_value: Mapped[str] = mapped_column(Text, nullable=False)
    decision: Mapped[str] = mapped_column(CHECK_DECISION, nullable=False)
    confidence: Mapped[int] = mapped_column(Integer, nullable=False)
    reason: Mapped[str] = mapped_column(String(255), nullable=False)
    cache_status: Mapped[str] = mapped_column(CACHE_STATUS, nullable=False)
    created_at: Mapped[datetime] = utc_now_column()

    __table_args__ = (
        Index("ix_check_history_user_created", "user_id", "created_at"),
        # Stored as a percentage, so the range is 0-100 and not 0-1.
        CheckConstraint("confidence between 0 and 100", name="confidence_range"),
    )


class DeveloperApiKey(Base):
    __tablename__ = "developer_api_keys"

    id: Mapped[int] = _pk()
    user_id: Mapped[int] = mapped_column(
        BigInteger, ForeignKey("users.id", ondelete="CASCADE"), nullable=False
    )
    label: Mapped[str] = mapped_column(String(80), nullable=False)
    key_prefix: Mapped[str] = mapped_column(String(24), nullable=False, unique=True)
    # Only the hash is ever stored. The secret is shown once, at creation, and never again.
    secret_hash: Mapped[str] = mapped_column(String(64), nullable=False, unique=True)
    # text[] rather than JSON, so a scope check is `scopes @> ARRAY['detect:image']` in SQL
    # with a GIN index, instead of loading the row and checking in Python.
    scopes: Mapped[list[str]] = mapped_column(ARRAY(Text), nullable=False)
    status: Mapped[str] = mapped_column(API_KEY_STATUS, nullable=False, server_default="active")
    rate_limit_per_minute: Mapped[int] = mapped_column(Integer, nullable=False, server_default="5")
    last_used_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    expires_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    created_at: Mapped[datetime] = utc_now_column()
    updated_at: Mapped[datetime] = utc_now_column()

    __table_args__ = (
        Index("ix_developer_api_keys_user_created", "user_id", "created_at"),
        Index("ix_developer_api_keys_scopes", "scopes", postgresql_using="gin"),
        CheckConstraint("rate_limit_per_minute between 1 and 10000", name="rate_limit_range"),
        # cardinality(), not array_length(): array_length of an empty array is NULL, and a
        # CHECK only rejects on FALSE — so the obvious spelling accepted exactly the rows
        # it was written to stop. cardinality returns 0.
        CheckConstraint("cardinality(scopes) >= 1", name="scopes_not_empty"),
        CheckConstraint("secret_hash ~ '^[a-f0-9]{64}$'", name="secret_hash_is_sha256"),
    )


class DeveloperApiUsage(Base):
    """Aggregate counters only.

    This table must never hold submitted text, policies, labels or model rationale. That is
    a tested privacy invariant, stated in the table comment so it survives contact with
    someone who has not read this docstring, and asserted against the live schema.
    """

    __tablename__ = "developer_api_usage"
    __table_args__ = (
        # Non-unique on purpose. It was unique on (api_key_id, created_at) once, and
        # concurrent requests in the same millisecond collided.
        Index("ix_developer_api_usage_key_created", "api_key_id", "created_at"),
        CheckConstraint("latency_ms between 0 and 600000", name="latency_range"),
        CheckConstraint("http_status between 100 and 599", name="http_status_range"),
        CheckConstraint("item_count >= 0", name="item_count_positive"),
        {
            "comment": (
                "Aggregate counters only. Never store submitted text, policies, labels or "
                "model rationale in this table."
            )
        },
    )

    id: Mapped[int] = _pk()
    api_key_id: Mapped[int] = mapped_column(
        BigInteger, ForeignKey("developer_api_keys.id", ondelete="CASCADE"), nullable=False
    )
    item_count: Mapped[int] = mapped_column(Integer, nullable=False)
    match_count: Mapped[int] = mapped_column(Integer, nullable=False, server_default="0")
    no_match_count: Mapped[int] = mapped_column(Integer, nullable=False, server_default="0")
    unavailable_count: Mapped[int] = mapped_column(Integer, nullable=False, server_default="0")
    latency_ms: Mapped[int] = mapped_column(Integer, nullable=False)
    http_status: Mapped[int] = mapped_column(Integer, nullable=False)
    created_at: Mapped[datetime] = utc_now_column()


class ImageUpload(Base):
    __tablename__ = "image_uploads"

    id: Mapped[int] = _pk()
    api_key_id: Mapped[int] = mapped_column(
        BigInteger, ForeignKey("developer_api_keys.id", ondelete="CASCADE"), nullable=False
    )
    # Content-addressed, so re-uploading identical bytes is idempotent.
    sha256: Mapped[str] = mapped_column(String(64), nullable=False, unique=True)
    mime_type: Mapped[str] = mapped_column(String(40), nullable=False)
    byte_size: Mapped[int] = mapped_column(Integer, nullable=False)
    width: Mapped[int | None] = mapped_column(Integer)
    height: Mapped[int | None] = mapped_column(Integer)
    subject: Mapped[str | None] = mapped_column(String(80))
    labels: Mapped[list[dict[str, Any]]] = mapped_column(JSONB, nullable=False)
    created_at: Mapped[datetime] = utc_now_column()

    __table_args__ = (
        Index("ix_image_uploads_key_created", "api_key_id", "created_at"),
        CheckConstraint("sha256 ~ '^[a-f0-9]{64}$'", name="sha256_is_digest"),
        CheckConstraint("byte_size > 0", name="byte_size_positive"),
    )


class AuditLog(Base):
    """Who did what, to which thing, and when.

    Written in the **same transaction** as the mutation it describes, so a change without
    its audit row is not possible. No outbox: an outbox exists to make a write and a
    cross-system notification atomic, and this lives in the same database as the mutation,
    which is strictly stronger.

    ``action`` is text rather than an enum so adding an audited action needs no migration;
    the allowed set is validated in the service layer, where a typo fails a test.
    """

    __tablename__ = "audit_log"

    id: Mapped[int] = _pk()
    occurred_at: Mapped[datetime] = utc_now_column()
    request_id: Mapped[str | None] = mapped_column(String(64))
    actor_type: Mapped[str] = mapped_column(AUDIT_ACTOR_TYPE, nullable=False)
    actor_user_id: Mapped[int | None] = mapped_column(
        BigInteger, ForeignKey("users.id", ondelete="SET NULL")
    )
    actor_key_id: Mapped[int | None] = mapped_column(
        BigInteger, ForeignKey("developer_api_keys.id", ondelete="SET NULL")
    )
    actor_label: Mapped[str | None] = mapped_column(Text)
    action: Mapped[str] = mapped_column(Text, nullable=False)
    target_type: Mapped[str] = mapped_column(Text, nullable=False)
    # Text, so a sha256 image id fits alongside a numeric policy id.
    target_id: Mapped[str | None] = mapped_column(Text)
    ip: Mapped[str | None] = mapped_column(INET)
    user_agent: Mapped[str | None] = mapped_column(Text)
    # Built from a per-action allowlist, never free-form: the audit trail records that a
    # policy's rules changed, not what the rules are.
    meta: Mapped[dict[str, Any]] = mapped_column(
        "metadata", JSONB, nullable=False, server_default="{}"
    )

    __table_args__ = (
        Index("ix_audit_log_occurred", "occurred_at"),
        Index("ix_audit_log_actor_user", "actor_user_id", "occurred_at"),
        Index("ix_audit_log_target", "target_type", "target_id", "occurred_at"),
        # Each actor kind must carry the identifier that makes it meaningful. A row saying
        # "an api_key did this" with no key id is not an audit record.
        CheckConstraint(
            "(actor_type = 'session_user'    AND actor_user_id IS NOT NULL) OR "
            "(actor_type = 'extension_token' AND actor_user_id IS NOT NULL) OR "
            "(actor_type = 'api_key'         AND actor_key_id  IS NOT NULL) OR "
            "(actor_type = 'system'          AND actor_user_id IS NULL AND actor_key_id IS NULL)",
            name="actor_shape",
        ),
    )
